repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 24.4.0 # Use the latest stable version
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2 # Use the latest stable version
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0 # Use the latest stable version
    hooks:
      - id: mypy
        args: [--ignore-missing-imports] # Adjust as needed for your project's strictness
